2023-07-01 20:32:33,797 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,799 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,800 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,800 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,811 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,813 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,816 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,820 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,821 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,822 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,823 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,825 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,827 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,827 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,828 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,836 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,837 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,838 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,842 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,843 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:33,844 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,111 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,112 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,114 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,116 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,117 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,119 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,119 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,121 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,122 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,125 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,127 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,127 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,128 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,128 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,129 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,159 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,160 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,161 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,162 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,163 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,164 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,164 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,165 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,166 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,166 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,168 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,170 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,170 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,171 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,172 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,173 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,202 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,203 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,205 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,206 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,207 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,208 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,210 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,210 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,211 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,212 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,212 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,214 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,217 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,220 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,221 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,222 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,223 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,223 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,224 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,224 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,226 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,226 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,253 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,254 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,256 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,258 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,258 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,259 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,259 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,261 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,262 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,263 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,264 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,267 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,268 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,269 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,273 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,274 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,275 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,276 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,277 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,278 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,279 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,280 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,281 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,321 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,322 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,323 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,323 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,325 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,327 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,327 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,328 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,329 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,331 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,332 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,333 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,334 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,335 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,336 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,336 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,338 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,339 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,340 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,341 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,342 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,344 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,345 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,346 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,380 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,382 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,383 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,384 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,386 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,388 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,388 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,390 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,391 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,391 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,392 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,393 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,394 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,395 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,395 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,396 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,396 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,419 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,420 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,420 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,422 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,423 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,424 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,425 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,426 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,427 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,428 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,429 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,430 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,431 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,432 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,432 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,433 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,434 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,435 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,461 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,462 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,463 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,464 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,465 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,466 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,467 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,468 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,470 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,471 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,472 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,473 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,474 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,475 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,476 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,477 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,478 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,479 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,480 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,482 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,484 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,485 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,486 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,487 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,488 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,515 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,517 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,519 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,520 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,521 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,522 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,523 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,524 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,524 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,525 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,526 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,526 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,527 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,527 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,528 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,529 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,529 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,531 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,532 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,532 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,533 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,534 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,536 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,536 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,537 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,538 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,567 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,568 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,569 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,570 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,571 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,574 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,575 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,576 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,578 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,579 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,580 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,583 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,586 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,587 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,588 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,589 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,591 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,591 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,592 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,593 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,593 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,594 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,595 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,596 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,597 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,598 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,600 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,632 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,633 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,634 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,635 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,637 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,638 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,639 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,640 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,641 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,641 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,642 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,642 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,643 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,644 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,644 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,645 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,646 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,647 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,648 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,669 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,670 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,671 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,672 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,672 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,674 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,674 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,676 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,677 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,678 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,679 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,680 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,680 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,681 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,683 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,685 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,686 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,687 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,689 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,690 ERROR brittney36@ccategoryk.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: brittney36@ccategoryk.com - this email is already in use.
2023-07-01 20:32:34,714 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,716 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,717 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,719 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,721 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,721 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,722 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,722 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,723 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,724 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,725 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,727 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,728 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,728 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,729 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,731 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,732 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,733 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,734 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,735 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,736 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,739 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,740 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,740 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,741 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,742 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,742 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,743 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,777 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,778 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,779 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,779 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,780 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,781 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,782 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,783 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,784 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,785 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,786 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,787 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,788 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,788 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,789 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,790 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,791 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,791 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,792 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,792 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,793 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,793 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,794 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,795 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,796 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,796 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,797 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,798 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
2023-07-01 20:32:34,798 ERROR 848belval848@gmail.com - this email is already in use.
Traceback (most recent call last):
  File "C:\Users\HP\Documents\a-level\GIT5\L19\test_L17\classes\employee_recruiter_developer.py", line 33, in validate
    raise EmailAlreadyExistsException(f"{email} - this email is already in use.")
L19.test_L17.classes.employee_recruiter_developer.EmailAlreadyExistsException: 848belval848@gmail.com - this email is already in use.
